import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
function easyTime() {
  return (
    <div>
      <Head>
        <title>Easy Time Complexity</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      {/* <img className="max-w-full" src="404.svg" alt="" /> */}
      <div className=" flex flex-col justify-center items-center m-auto max-w-screen-lg">
        <h1 className="mt-24 font-medium text-4xl text-center">
          Easy Time Complexity
        </h1>
        <p className="mt-10 text-xl md:w-1/2 text-center">
          Use OpenAI to evaluate the complexity of your functions.
        </p>
        <GithubButton href="https://github.com/LihaoWang/easy-time-complexity" />
        <DemoButton href="https://easy-time-complexity.vercel.app/" />
        <img src="images/easy-time-1.png" />
        <img src="images/easy-time-2.png" />
      </div>
      <Footer href="/easyTime" />
    </div>
  );
}

export default easyTime;
