import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
import ProjectHeader from "../components/ProjectHeader";
import ProjectDescription from "../components/ProjectDescription";
import { useTheme } from "../ToggleContext";
function easyTime() {
  const darkTheme = useTheme();
  const description = `Use OpenAI to evaluate the complexity of your functions.`;
  return (
    <div className={darkTheme ? "dark" : ""}>
      <Head>
        <title>Easy Time Complexity</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      {/* <img className="max-w-full" src="404.svg" alt="" /> */}
      <div className="w-full dark:bg-black">
        <div className=" flex flex-col justify-center items-center m-auto max-w-screen-lg">
          <ProjectHeader text="Easy Time Complexity" />
          <ProjectDescription text={description} />
          <GithubButton href="https://github.com/LihaoWang/easy-time-complexity" />
          <DemoButton href="https://easy-time-complexity.vercel.app/" />
          <img src="images/easy-time-1.png" />
          <img src="images/easy-time-2.png" />
        </div>
        <Footer href="/easyTime" />
      </div>
    </div>
  );
}

export default easyTime;
