import Head from "next/head";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Leo Wang | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Nav />
        <div className="w-5/6 m-auto max-w-screen-lg">
          <Hero />
          <Projects />
        </div>
        <Footer href="/" />
      </main>
    </div>
  );
}
