import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
function spacestagram() {
  return (
    <div>
      <Head>
        <title>Spacestagram</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <div className="flex flex-col justify-center items-center m-auto max-w-screen-lg">
        <h1 className="mt-24 font-medium text-4xl text-center px-5">
          Spacestagram
        </h1>
        <p className="mt-10 text-xl md:w-1/2 text-center px-5">
          Spacestagram displays stunning space pictures fetched from NASA APOD
          (Astronomy Picture of the Day) API. Additionally, users will be able
          to like and share the pictures easily.
        </p>
        <GithubButton href="https://github.com/LihaoWang/spacestagram" />
        <DemoButton href="https://stagram.space/" />

        <img className="mb-5" src="images/space-1.gif" />
        <img src="images/space-2.png" />
      </div>
      <Footer href="/spacestagram" />
    </div>
  );
}

export default spacestagram;
