import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
import ProjectHeader from "../components/ProjectHeader";
import ProjectDescription from "../components/ProjectDescription";
import { useTheme } from "../ToggleContext";
function spacestagram() {
  const darkTheme = useTheme();
  const description = `          Spacestagram displays stunning space pictures fetched from NASA APOD
  (Astronomy Picture of the Day) API. Additionally, users will be able
  to like and share the pictures easily.`;
  return (
    <div className={darkTheme ? "dark" : ""}>
      <Head>
        <title>Spacestagram</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <div className="w-full dark:bg-black">
        <div className="flex flex-col justify-center items-center m-auto max-w-screen-lg">
          <ProjectHeader text="Spacestagram" />
          <ProjectDescription text={description} />
          <GithubButton href="https://github.com/LihaoWang/spacestagram" />
          <DemoButton href="https://stagram.space/" />

          <img className="mb-5" src="images/space-1.gif" />
          <img src="images/space-2.png" />
        </div>
        <Footer href="/spacestagram" />
      </div>
    </div>
  );
}

export default spacestagram;
