import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
function ulinks() {
  return (
    <div>
      <Head>
        <title>Ulinks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />

      <div className="flex flex-col justify-center items-center m-auto max-w-screen-lg ">
        <h1 className="mt-24 font-medium text-4xl text-center">Ulinks</h1>
        <p className="mt-10 text-xl md:w-1/2 text-center">
          Ulinks is bio link platform where users could share their links,
          products, videos, and more on one page.
        </p>
        <GithubButton href="https://github.com/LihaoWang/ulinks" />
        <DemoButton href="https://www.ulinks.cool/" />

        <img src="images/ulinks1.png" />
        <img src="images/ulinks2.png" />
        <img src="images/ulinks3.png" />
      </div>
      <Footer href="/ulinks" />
    </div>
  );
}

export default ulinks;
