import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import ProjectHeader from "../components/ProjectHeader";
import ProjectDescription from "../components/ProjectDescription";
import Head from "next/head";
import Footer from "../components/Footer";
import { useTheme } from "../ToggleContext";
function ulinks() {
  const darkTheme = useTheme();
  const description =
    "Ulinks is bio link platform where users could share their links, products, videos, and more on one page.";
  return (
    <div className={darkTheme ? "dark" : ""}>
      <Head>
        <title>Ulinks</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <div className="w-full dark:bg-black">
        <div className="flex flex-col justify-center items-center m-auto max-w-screen-lg">
          <ProjectHeader text="Ulinks" />
          <ProjectDescription text={description} />
          <GithubButton href="https://github.com/LihaoWang/ulinks" />
          <DemoButton href="https://www.ulinks.cool/" />

          <img className="dark:bg-black" src="images/ulinks1.png" />
          <img src="images/ulinks2.png" />
          <img src="images/ulinks3.png" />
        </div>
        <Footer href="/ulinks" />
      </div>
    </div>
  );
}

export default ulinks;
