import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
import ProjectHeader from "../components/ProjectHeader";
import ProjectDescription from "../components/ProjectDescription";
import { useTheme } from "../ToggleContext";
function xchange() {
  const darkTheme = useTheme();
  const description = `Xchange 2.0 is a cryptocurrency tracker & calculator that supports Web3 wallet login. Users can easily track cryptocurrency rates and see detailed stats of each cryptocurrency in the application.`;
  return (
    <div className={darkTheme ? "dark" : ""}>
      <Head>
        <title>Xchange 2.0</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <div className="w-full dark:bg-black">
        <div className=" flex flex-col justify-center items-center m-auto max-w-screen-lg">
          <ProjectHeader text="Xchange 2.0" />
          <ProjectDescription text={description} />
          <GithubButton href="https://github.com/LihaoWang/crypto-next-app" />
          <DemoButton href="https://crypto.x-change.xyz" />

          <img className="" src="images/xchange2-1.png" />
          <img className="mb-3" src="images/xchange2-4.png" />
          <img className="" src="images/xchange2-2.png" />
          <img className="" src="images/xchange2-3.png" />
        </div>
        <Footer href="/xchange-2" />
      </div>
    </div>
  );
}

export default xchange;
