import React from "react";
import Nav from "../components/Nav";
import GithubButton from "../components/GithubButton";
import DemoButton from "../components/DemoButton";
import Head from "next/head";
import Footer from "../components/Footer";
import ProjectHeader from "../components/ProjectHeader";
import ProjectDescription from "../components/ProjectDescription";
import { useTheme } from "../ToggleContext";
function xchange() {
  const darkTheme = useTheme();
  const description = `Xchange is a unique currency converter app that displays up to 170
  currency exchange rates on one page. Users can easily copy the
  converted results, for maximum efficiency.`;
  return (
    <div className={darkTheme ? "dark" : ""}>
      <Head>
        <title>Xchange</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <div className="w-full dark:bg-black">
        <div className=" flex flex-col justify-center items-center m-auto max-w-screen-lg">
          <ProjectHeader text="Xchange" />
          <ProjectDescription text={description} />
          <GithubButton href="https://github.com/LihaoWang/xchange" />
          <DemoButton href="https://x-change.xyz" />

          <img className="mb-2" src="images/xchange-0.png" />
          <img className="mb-2" src="images/xchange-1.png" />
          <img className="mb-2" src="images/xchange-2.png" />
          <img className="mb-2" src="images/xchange-3.png" />
        </div>
        <Footer href="/xchange" />
      </div>
    </div>
  );
}

export default xchange;
